# Generated by pulserpc - do not edit

# This file contains example code showing how to use the PulseRPC client
# The client automatically discovers interfaces from the server

from pulserpc import HttpTransport, Client

# Example: Create a client and call a method
# 
# transport = HttpTransport("http://localhost:8080")
# client = Client(transport)
#
# result = client.CatalogService.listProducts()
#
# result = client.CartService.addToCart(request=...)
#
# result = client.OrderService.createOrder(request=...)
#
# The client automatically fetches the IDL from the server and
# makes interfaces available as attributes (e.g., client.CatalogService)
