# Generated by pulserpc - do not edit

# Abstract service classes
# Implement these classes to create your service

import abc
from pulserpc import RPCError
from .types import Product, CartItem, Cart, Address, Order, AddToCartRequest, CreateOrderRequest, CheckoutResponse, OrderStatus, PaymentMethod

class CatalogService(abc.ABC):

    @abc.abstractmethod
    def listProducts(self, ctx):
        pass

    @abc.abstractmethod
    def getProduct(self, ctx, productId):
        pass


class CartService(abc.ABC):

    @abc.abstractmethod
    def addToCart(self, ctx, request):
        pass

    @abc.abstractmethod
    def getCart(self, ctx, cartId):
        pass

    @abc.abstractmethod
    def clearCart(self, ctx, cartId):
        pass


class OrderService(abc.ABC):

    @abc.abstractmethod
    def createOrder(self, ctx, request):
        pass

    @abc.abstractmethod
    def getOrder(self, ctx, orderId):
        pass


