# Generated by pulserpc - do not edit

# Abstract service classes
# Implement these classes to create your service

import abc
from pulserpc import RPCError
from .types import Product, CartItem, Cart, Address, Order, AddToCartRequest, CreateOrderRequest, CheckoutResponse, OrderStatus, PaymentMethod

class CatalogService(abc.ABC):

    @abc.abstractmethod
    def listProducts(self, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass

    @abc.abstractmethod
    def getProduct(self, productId, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass


class CartService(abc.ABC):

    @abc.abstractmethod
    def addToCart(self, request, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass

    @abc.abstractmethod
    def getCart(self, cartId, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass

    @abc.abstractmethod
    def clearCart(self, cartId, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass


class OrderService(abc.ABC):

    @abc.abstractmethod
    def createOrder(self, request, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass

    @abc.abstractmethod
    def getOrder(self, orderId, ctx=None):
        # ctx is for transport-level metadata (headers, auth) not suitable for request body
        pass


