# Generated by pulserpc - do not edit

# Data types and enums for this namespace

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any

@dataclass
class Product:
    """Data class for Product"""

    productId: str = field(default=...)
    name: str = field(default=...)
    description: str = field(default=...)
    price: float = field(default=...)
    stock: int = field(default=...)
    imageUrl: Optional[str] = None

@dataclass
class CartItem:
    """Data class for CartItem"""

    productId: str = field(default=...)
    quantity: int = field(default=...)
    price: float = field(default=...)

@dataclass
class Cart:
    """Data class for Cart"""

    cartId: str = field(default=...)
    items: List['CartItem'] = field(default=...)
    subtotal: float = field(default=...)

@dataclass
class Address:
    """Data class for Address"""

    street: str = field(default=...)
    city: str = field(default=...)
    state: str = field(default=...)
    zipCode: str = field(default=...)
    country: str = field(default=...)

@dataclass
class Order:
    """Data class for Order"""

    orderId: str = field(default=...)
    cart: 'Cart' = field(default=...)
    shippingAddress: 'Address' = field(default=...)
    paymentMethod: 'PaymentMethod' = field(default=...)
    status: 'OrderStatus' = field(default=...)
    total: float = field(default=...)
    createdAt: int = field(default=...)

@dataclass
class AddToCartRequest:
    """Data class for AddToCartRequest"""

    cartId: Optional[str] = None
    productId: str = field(default=...)
    quantity: int = field(default=...)

@dataclass
class CreateOrderRequest:
    """Data class for CreateOrderRequest"""

    cartId: str = field(default=...)
    shippingAddress: 'Address' = field(default=...)
    paymentMethod: 'PaymentMethod' = field(default=...)

@dataclass
class CheckoutResponse:
    """Data class for CheckoutResponse"""

    orderId: str = field(default=...)
    message: Optional[str] = None

class OrderStatus:
    """Enum for OrderStatus"""
    pending = "pending"
    paid = "paid"
    shipped = "shipped"
    delivered = "delivered"
    cancelled = "cancelled"

class PaymentMethod:
    """Enum for PaymentMethod"""
    credit_card = "credit_card"
    debit_card = "debit_card"
    paypal = "paypal"
    apple_pay = "apple_pay"

# Standard JSON-RPC error codes
class ErrJsonRpc:
    """Standard JSON-RPC error codes"""

    ParseError = -32700  # Invalid JSON was received
    InvalidRequest = -32600  # The JSON sent is not a valid Request object
    MethodNotFound = -32601  # The method does not exist or is not available
    InvalidParams = -32602  # Invalid method parameter(s)
    InternalError = -32603  # Internal JSON-RPC error

# Error codes for this namespace
class Err:
    """Error codes for this namespace"""

    CartNotFound = 1001
    CartEmpty = 1002
    PaymentFailed = 1003
    OutOfStock = 1004
    InvalidAddress = 1005

