package generator

import (
	"fmt"
	"os"
	"path/filepath"
)

// PythonNamespacePaths holds the resolved output paths for Python multi-namespace generation
type PythonNamespacePaths struct {
	// BaseDir is the root output directory (from -dir flag)
	BaseDir string
	// PackageBase is the Python package prefix (from -package flag), e.g., "myapp.lib.rpc"
	PackageBase string
}

// ResolveNamespaceDir returns the output directory path for a given namespace.
// When PackageBase is set, namespaces are placed under {BaseDir}/{PackageBase}/{namespace}/
// For the empty/default namespace with PackageBase, returns {BaseDir}/{PackageBase}/
// For named namespaces without PackageBase, returns {BaseDir}/{namespace}/
func (p PythonNamespacePaths) ResolveNamespaceDir(namespace string) string {
	base := p.BaseDir
	if p.PackageBase != "" {
		base = filepath.Join(append([]string{p.BaseDir}, splitByDot(p.PackageBase)...)...)
	}
	if namespace == "" {
		return base
	}
	return filepath.Join(base, namespace)
}

// ResolveRuntimeDir returns the output directory path for the pulserpc runtime.
// When PackageBase is set, returns {BaseDir}/{PackageBase}/pulserpc/
// When PackageBase is empty, returns {BaseDir}/pulserpc/
func (p PythonNamespacePaths) ResolveRuntimeDir() string {
	base := p.BaseDir
	if p.PackageBase != "" {
		base = filepath.Join(append([]string{p.BaseDir}, splitByDot(p.PackageBase)...)...)
	}
	return filepath.Join(base, "pulserpc")
}

// ResolveOutputPath returns the full path for a file within a namespace directory.
// For example: ResolveOutputPath("common", "types.py") -> {BaseDir}/common/types.py
func (p PythonNamespacePaths) ResolveOutputPath(namespace, filename string) string {
	dir := p.ResolveNamespaceDir(namespace)
	return filepath.Join(dir, filename)
}

// EnsureNamespaceDir creates the directory for a namespace if it doesn't exist.
// Returns the resolved directory path.
func (p PythonNamespacePaths) EnsureNamespaceDir(namespace string) (string, error) {
	dir := p.ResolveNamespaceDir(namespace)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	return dir, nil
}

// EnsureRuntimeDir creates the runtime directory if it doesn't exist.
// Returns the resolved directory path.
func (p PythonNamespacePaths) EnsureRuntimeDir() (string, error) {
	dir := p.ResolveRuntimeDir()
	if err := os.MkdirAll(dir, 0755); err != nil {
		return "", err
	}
	return dir, nil
}

// CollectNamespaces returns a sorted list of all namespaces present in the IDL.
// The empty namespace (for types without a namespace) is excluded from the list
// unless it's the only namespace present.
func CollectNamespaces(namespaceMap map[string]*NamespaceTypes) []string {
	namespaces := make([]string, 0)
	hasEmptyNamespace := false

	for ns := range namespaceMap {
		if ns == "" {
			hasEmptyNamespace = true
			continue
		}
		namespaces = append(namespaces, ns)
	}

	// If no named namespaces exist, include the empty namespace for single-namespace mode
	if len(namespaces) == 0 && hasEmptyNamespace {
		namespaces = append(namespaces, "")
	}

	return namespaces
}

// NewPythonNamespacePaths creates a new PythonNamespacePaths instance
func NewPythonNamespacePaths(baseDir, packageBase string) PythonNamespacePaths {
	return PythonNamespacePaths{
		BaseDir:     baseDir,
		PackageBase: packageBase,
	}
}

// EnsureAllNamespaceDirs creates directories for all namespaces in the IDL.
// This handles both include-driven (multiple namespaces) and single-file generation.
// Returns a map of namespace -> directory path.
func (p PythonNamespacePaths) EnsureAllNamespaceDirs(namespaceMap map[string]*NamespaceTypes) (map[string]string, error) {
	dirs := make(map[string]string)

	// Ensure runtime directory
	if _, err := p.EnsureRuntimeDir(); err != nil {
		return nil, err
	}

	// Ensure directory for each namespace
	for ns := range namespaceMap {
		dir, err := p.EnsureNamespaceDir(ns)
		if err != nil {
			return nil, err
		}
		dirs[ns] = dir
	}

	return dirs, nil
}

// GenerateInitPy writes an __init__.py file in the given directory.
// The file is idempotent - safe to regenerate without corruption.
// When packageBase is set, includes a relative import of the pulserpc runtime.
func (p PythonNamespacePaths) GenerateInitPy(namespace string) error {
	dir := p.ResolveNamespaceDir(namespace)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	initPath := filepath.Join(dir, "__init__.py")

	var content string
	if p.PackageBase != "" && namespace == "" {
		// Root namespace with package base - import pulserpc runtime
		runtimePkg := p.PackageBase + ".pulserpc"
		content = "# Generated by pulserpc - do not edit\n"
		content += "# This file makes the namespace directory a Python package.\n\n"
		content += fmt.Sprintf("from %s import RPCError, Server, Client, Contract, HttpTransport, InProcTransport\n", runtimePkg)
	} else if p.PackageBase != "" {
		// Named namespace with package base
		content = "# Generated by pulserpc - do not edit\n"
		content += "# This file makes the namespace directory a Python package.\n"
	} else {
		// No package base - minimal init file
		content = "# Generated by pulserpc - do not edit\n"
		content += "# This file makes the namespace directory a Python package.\n"
	}

	return os.WriteFile(initPath, []byte(content), 0644)
}

// GenerateAllInitPyFiles writes __init__.py files for all namespaces in the IDL.
// This is idempotent - safe to call multiple times.
func (p PythonNamespacePaths) GenerateAllInitPyFiles(namespaceMap map[string]*NamespaceTypes) error {
	namespaces := CollectNamespaces(namespaceMap)

	if p.PackageBase != "" {
		parts := splitByDot(p.PackageBase)
		for i := range parts {
			dir := filepath.Join(append([]string{p.BaseDir}, parts[:i+1]...)...)
			initPath := filepath.Join(dir, "__init__.py")
			content := "# Generated by pulserpc - do not edit\n"
			content += "# This file makes the directory a Python package.\n"
			if err := os.WriteFile(initPath, []byte(content), 0644); err != nil {
				return err
			}
		}
	}

	for _, ns := range namespaces {
		if err := p.GenerateInitPy(ns); err != nil {
			return err
		}
	}
	return nil
}

// splitByDot splits a string by dots (used for Python package paths)
func splitByDot(s string) []string {
	result := make([]string, 0)
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '.' {
			if i > start {
				result = append(result, s[start:i])
			}
			start = i + 1
		}
	}
	if start < len(s) {
		result = append(result, s[start:])
	}
	return result
}
